# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

#config.vm.provision "shell", inline: "echo Apache_server_install && yum update -y && yum install -y httpd && chkconfig httpd on && /etc/init.d/httpd start"

$script = <<SCRIPT
echo Provisioning...
echo "192.168.33.70    puppet" >> /etc/hosts
rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
yum install -y puppet
puppet resource service puppet ensure=running enable=true
puppet agent -t
SCRIPT

config.vm.provision "shell", inline:$script  # provisioning

#config.vm.provision "ansible" do |ansible|
 #   ansible.playbook = 'provisionz.yml'
  #  ansible.verbose = 'vv'
 # end

config.vm.define :vm02 do |vm02|
    vm02.vm.box = "sbeliakou/centos-6.7-x86_64"
    vm02.vm.hostname = "puppet-node02"
    vm02.vm.network "private_network", ip: "192.168.33.72"
    #vm02.vm.network "forwarded_port", guest: 80, host: 8181
    #vm02.vm.synced_folder ".", "/vagrant", disabled: true
    #vm02.vm.synced_folder "/root/vagrant/share2", "/vagrant-vm-share", owner: "root", group: "root"
    	vm02.vm.provider "virtualbox" do |vb02|
		vb02.name = "puppet-node02"
		vb02.customize ["modifyvm", :id, "--memory", 2048]
		vb02.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
   end
end
